import { Geist, Geist_Mono } from "next/font/google";
import DashNav from "./DashNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Stocks Dashboard",
  description: "Generated by create next app",
};

export default function Dasboardlayout({ children }) {
  return (
    <>
      <DashNav />
      {children}
    </>
  );
}
